version: '3.4'

services:
  app:
    restart: always
    build: .
    depends_on:
      - ch_server
    ports:
      - "8080:8080"

  ch_server:
    image: yandex/clickhouse-server:18.10
    ports:
      - "8123:8123"
    restart: always


