app: web
server:
  port: 8080
  readTimeout: 5s
database:
  #host: ch_server
  host: ch_server
  port: 8123
  database: test
  user: default
  password:
workers:
  buffer: 150000
  default: 1
  analytics: 500
  db: 70